### ISSUE TITLE
Few notes

### ISSUE THREAD

**Issue by yazd** [bakkdoor/gumbo-d#1]
First of all, the library looks very useful. Thank you for your work.

Second of all, it's nothing major, but just as a suggestion, you might want to follow the D style for the enum members names to fit more into other D code. (http://dlang.org/dstyle.html)
If you prefer, I can do a pull request for that.

Other than that, it might be good to have a link to this library on the original gumbo github page as the other bindings. (https://github.com/google/gumbo-parser)

Thanks again.

**Comment by bakkdoor** [comment]
Hey,
thanks for the code style suggestions, I'll change the enum cases to camelCase :)

And yeah a link on the gumbo-parser repo to this library would be good, I'll create a request to add it later.

**Comment by bakkdoor** [comment]
Just saw that the pull request was accepted and merged ( https://github.com/google/gumbo-parser/pull/32 )
Thanks again and let me know if there are any other suggestions.

**Comment by yazd** [comment]
Ahh great. Thank you for the good work.
I'll be experimenting more with gumbo-d and if anything turns out I'll let you know.

**Comment by bakkdoor** [comment]
Great, thanks!
