### ISSUE TITLE
Wrong enum

### ISSUE THREAD

**Issue by zek** [bakkdoor/gumbo-d#2]
I guess official gumbo parser has changed their enum struct and this is not compatible with latest gumbo anymore.

class Element : Node {
    enum Tag {
        html, head, title, base, link, meta, style, script, noscript, template_, body_, article,
        section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header,
        footer, address, p, hr, pre, blockquote, ol, ul, li, dl, dt, dd,
        figure, figcaption, main, div, a, em, strong, small, s, cite, q, dfn, abbr,
        time, code, var, samp, kbd, sub, sup, i, b, mark, ruby, rt, rp, bdi,
        bdo, span, br, wbr, ins, del, image, img, iframe, embed, object, param,
        video, audio, source, track, canvas, map, area, math, mi, mo, mn, ms,
        mtext, mglyph, malignmark, annotationXML, svg, foreignObject, desc,
        table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th, form,
        fieldset, legend, label, input, button, select, datalist, optgroup,
        option, textarea, keygen, output, progress, meter, details, summary,
        command, menu, applet, acronym, bgsound, dir, frame, frameset,
        noFrames, isIndex, listing, xmp, nextId, noEmbed, plainText, rb,
        strike, baseFont, big, blink, center, font, marquee, multicol, nobr,
        spacer, tt, u, unknown, last,
    };

**Comment by SerialVelocity** [comment]
Hey, this is still wrong. Is it possible for this to be fixed or is this project abandoned?
The dub doesn't work with the latest version of gumbo.
